[tool.poetry]
name = "python-template"
version = "0.1.0"
description = "Run a Flask server that checks for changes in Linux network interface configuration by polling it, and exposes Prometheus metrics when changes are detected."
authors = ["Manuel Gómez <targen@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
flask = "^3.0.0"
netaddr = "^0.9.0"
#netifaces = "*"
prometheus_client = "^0.18.0"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"